[package]
name = "mock_rest_server"
version = "1.0.0-rc.2"
authors = ["Substratum Services"]
copyright = "Copyright (c) 2017-2019, Substratum LLC (https://substratum.net) and/or its affiliates. All rights reserved."
edition = "2018"

[dependencies]
rocket = "0.4.2"
