name: s3-release

on:
  workflow_run:
    workflows: [ci-matrix]
    types:
      - completed

jobs:
  deploy_to_versioned_s3:
       if: startsWith(github.head_ref, 'v*') != true
       runs-on: ubuntu-latest
       steps:
        - uses: actions/checkout@v3
        - name: Download artifacts from PR
          run: |
            mkdir download
            cd download
            gh run download ${{ github.event.workflow_run.id }}
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Display structure of downloaded files
          run: ls -R download
        - name: S3 Sync
          uses: jakejarvis/s3-sync-action@v0.5.1
          with:
           args: --acl private --follow-symlinks --delete
          env:
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: 'us-west-2'
            DEST_DIR: 'Node/${{ github.head_ref }}'
            SOURCE_DIR: download
  deploy_to_latest_s3:
       if: startsWith(github.head_ref, 'v*') == true
       runs-on: ubuntu-latest
       steps:
        - uses: actions/checkout@v3
        - name: Download artifacts from PR
          run: |
            mkdir download
            cd download
            gh run download ${{ github.event.workflow_run.id }}
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Display structure of downloaded files
          run: ls -R download
        - name: S3 Sync
          uses: jakejarvis/s3-sync-action@v0.5.1
          with:
           args: --acl private --follow-symlinks --delete
          env:
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: 'us-west-2'
            DEST_DIR: 'Node/latest'
            SOURCE_DIR: download
